Repository wecode-bootcamp-korea/41-1st-Weat-frontend, pull requests merged in 2023-01, with the labels that each got.

#8 41기 [김지환] Modify : Footer 레이아웃 구현(리뷰반영)
  package-lock.json
  package.json
  src/Router.js
  src/components/footer/Footer.js
  src/components/footer/Footer.scss
  src/pages/cart/Cart.js
  src/pages/category/Category.js
  src/pages/category/detail/Detail.js
  src/pages/login/Login.js
  src/pages/main/Main.js
  src/pages/signup/Signup.js
Labels: 멘토 리뷰 요청, 수정 요청

#7 41기 [박정은] ADD : SignUp 레이아웃 수정
  package-lock.json
  package.json
  src/Router.js
  src/pages/login/Login.scss
  src/pages/signup/Signup.js
  src/pages/signup/Signup.scss
Labels: 멘토 리뷰 요청

#9 41기 [배경민] ADD : DetailPage 레이아웃 구현
  package-lock.json
  public/data/dataCartegory.json
  public/data/mockdata.json
  src/Router.js
  src/pages/category/detail/Detail.js
  src/pages/category/detail/Detail.scss
Labels: 멘토 리뷰 요청

#12 41기 [배경민] ADD : CategoryPage 레이아웃 구현
  public/images/grill.jpg
  public/images/meat.jpg
  pull_request_template.md
  src/pages/cart/Cart.scss
  src/pages/category/Category.js
  src/pages/category/Category.scss
  src/pages/main/Main.scss
Labels: 수정 요청

#10 41기 [박정은] ADD : Login 레이아웃 구현 수정
  src/pages/login/Login.js
  src/pages/login/Login.scss
  src/styles/common.scss
Labels: 멘토 리뷰 요청

#13 41기 [김지환] Modify : Nav 레이아웃 리뷰반영 수정
  .vscode/launch.json
  package-lock.json
  public/images/logo.png
  src/Router.js
  src/components/nav/Nav.js
  src/components/nav/Nav.scss
Labels: 완료

#18 41기 [김지환] nav 레이아웃,css 일부 수정
  src/components/nav/Nav.scss
Labels: 멘토 리뷰 요청

#5 41기 [황선용] Modify: 장바구니 레이아웃 리뷰 반영 및 추가 기능 구현
  package-lock.json
  public/data/meatData.json
  src/pages/cart/Cart.js
  src/pages/cart/Cart.scss
  src/pages/cart/Cartaside.js
  src/pages/cart/Cartaside.scss
  src/pages/cart/Cartcount.js
  src/pages/cart/Cartcount.scss
Labels: 멘토 리뷰 요청

#11 41기 [김지환] Add : 메인 페이지 레이아웃 구현
  package-lock.json
  public/data/dataCartegory.json
  public/images/grill.jpg
  public/images/meat.jpg
  public/images/porkbelly.jpg
  public/images/slide1.jpg
  src/pages/category/detail/Detail.js
  src/pages/main/Item.js
  src/pages/main/Main.js
  src/pages/main/Main.scss
Labels: 멘토 리뷰 요청

#17 41기 [박정은] ADD : Login 기능 구현 통신완료
  src/pages/login/Login.js
  src/pages/login/Login.scss
Labels: 멘토 리뷰 요청

#15 41기 [박정은] ADD : 회원가입 기능 구현완료
  src/pages/payment/Payment.scss
  src/pages/signup/Signup.js
  src/pages/signup/Signup.scss
  src/styles/common.scss
Labels: 완료

#22 41기 [배경민] detail 에서 장바구니로 상품정보 보내기
  src/apiData.js
  src/pages/category/detail/Detail.js
  src/pages/login/Login.js
Labels: 완료

#23 Modify : main fetch 오류 수정
  src/apiData.js
  src/pages/cart/Cart.js
  src/pages/category/Category.js
  src/pages/category/detail/Detail.js
  src/pages/login/Login.js
  src/pages/main/Main.js
  src/pages/signup/Signup.js
Labels: 완료

#19 41기 [배경민] ADD : 구매 팝업기능
  package-lock.json
  public/data/mockdata.json
  src/pages/category/Category.js
  src/pages/category/Category.scss
  src/pages/category/CategoryItem.js
  src/pages/category/Popup.js
  src/pages/category/Popup.scss
Labels: 완료

#21 41기 [박정은] ADD : Payment 레이아웃
  public/images/next.png
  public/images/payment.png
  src/Router.js
  src/apiData.js
  src/pages/main/Main.js
  src/pages/payment/Payment.js
  src/pages/payment/Payment.scss
  src/pages/payment/PaymentList.js
  src/pages/payment/PaymentList.scss
Labels: 멘토 리뷰 요청

#25 41기 [배경민] : Modify : 머지 실수로 재업로드
  src/pages/category/Category.js
  src/pages/category/CategoryItem.js
Labels: 완료

#24 41기 [김지환] nav 장바구니 카운팅 구현, 로그인,로그아웃시 렌더링 구현
  src/components/nav/Nav.js
  src/components/nav/Nav.scss
  src/pages/main/Main.js
Labels: 완료

#30 41기 [배경민] : Category page 통신에 맞게 수정
  src/apiData.js
  src/pages/category/Category.js
  src/pages/category/CategoryItem.js
Labels: 완료

#31 41기 [배경민] Detail page 통신에 맞게 수정
  src/pages/category/detail/Detail.js
Labels: 멘토 리뷰 요청

#32 41기 [배경민] : ADD 카테고리페이지에서 장바구니 담기 및 장바구니이동기능
  src/pages/category/Popup.js
Labels: 완료

#29 41기 [박정은] ADD : Payment 기능 구현중
  src/pages/payment/Payment.js
  src/pages/payment/PaymentList.js
  src/pages/payment/PaymentList.scss
Labels: 완료

#26 [41기 황선용] ADD : PaymentFinal 레이아웃 및 기능구현
  public/data/meatData.json
  public/data/mockdata.json
  src/Router.js
  src/pages/cart/Cart.js
  src/pages/cart/Cartcount.js
  src/pages/paymentfinal/PaymentFinal.js
  src/pages/paymentfinal/PaymentFinal.scss
Labels: 완료

#33 41기 [김지환] Modify : 장바구니,바로구매시 새로고침 수정
  src/pages/main/Main.scss
  src/pages/main/Popup.js
Labels: 완료

#27 [41기 황선용] Modify: Cart API 수정
  src/pages/cart/Cart.js
  src/pages/cart/Cart.scss
  src/pages/cart/Cartaside.js
  src/pages/cart/Cartcount.js
Labels: 멘토 리뷰 요청

#34 [41기 황선용] Modify: PaymentFinal, Payment 수정
  src/Router.js
  src/pages/payment/Payment.js
  src/pages/paymentfinal/PaymentFinal.js
Labels: 완료
